### ISSUE TITLE
Want to know more about the limitation

### ISSUE THREAD

**Issue by sonu-drip** [fingerprintjs/fingerprintjs-ios#48]
Does the deviceId or fingerprint change on this two cases?

- User can attach iPhone to MacOS and delete the value in keychain manually
- User can create a new apple id and the keychains will be renewed

**Comment by mgutski** [comment]
Hi @sonu-drip and thanks for reaching out to us!

> User can attach iPhone to MacOS and delete the value in keychain manually

The keychain item containing the device ID is marked with [kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly](https://developer.apple.com/documentation/security/ksecattraccessibleafterfirstunlockthisdeviceonly) flag, meaning that it is **excluded** from iCloud backup. With that said, it is stored in a sandboxed keychain and there is no easy way to remove it. However, assuming a jailbroken iDevice, one could manipulate the keychain and remove the item at question. In such a case, provided that you also reinstall the app, the device ID would change. Another scenario where a new device ID will be created is if you factory reset your iDevice (Settings -> General -> Transfer or Reset iPhone -> Erase All Content and Settings). Only the **stable fingerprint** will survive the factory reset (see [Fingerprint Stability Levels](https://github.com/fingerprintjs/fingerprintjs-ios#fingerprint-stability-levels) for details), but one must note that this particular fingerprint is **highly prone to ID collisions**.

Detecting those kind of potentially fraudulent activities is beyond the capabilities of the OSS library. If you are interested in detecting compromised devices, **including those that were factory reset**, then please check out our [Fingerprint Pro iOS SDK](https://dev.fingerprint.com/docs/ios).

> User can create a new apple id and the keychains will be renewed

If you go through factory reset and set up the device with your new Apple ID, then a new device ID will be created. See the above explanation.

**Comment by sonu-drip** [comment]
Thank you for detailed information. @mgutski . Closing this.

**Comment by costapombo** [comment]
>  In such a case, provided that you also reinstall the app, the device ID would change. 

It's important to keep in mind that on iOS, uninstalling the app won't remove keychain items. 
If the app is reinstalled those items will be accessible.

**Comment by mgutski** [comment]
> It's important to keep in mind that on iOS, uninstalling the app won't remove keychain items.
If the app is reinstalled those items will be accessible.

That's correct, provided that the keychain hasn't been tampered with and my answer concerns a specific scenario that involves a jailbroken iDevice.
