### ISSUE TITLE
[Feature] iOS Privacy Manifest Support for 1.4.1 version

### ISSUE THREAD

**Issue by HithakshiK** [fingerprintjs/fingerprintjs-ios#49]
Updating to 1.5.0 would result in SDK generating new fingerprint which doesn't fit our use case. Please help us by providing privacy manifest file for 1.4.1 version. 🙏

**Comment by mgutski** [comment]
Hi @HithakshiK,

Our FingerprintJS OSS library does not include a privacy manifest file and there are no plans to change that. Please note that the OSS library, as opposed to its [Pro counterpart](https://github.com/fingerprintjs/fingerprintjs-pro-ios), is not distributed as a binary framework. You are free to use SwiftPM and statically link the OSS library to your project.

With that said, you may still use v1.4.1 by adding one of the [available reasons for use of disk space APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278397) to your app’s privacy manifest file. Though, if you decide to do so, please be aware that we cannot guarantee that your won't be rejected during App Review. It all depends on your use case and your app's specifics.

For more information on creating a privacy manifest file, see [Create a privacy manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files#4284009) instructions provided by Apple. For reference, you can also take a look at the [privacy manifest file](https://github.com/fingerprintjs/fingerprint-device-intelligence-ios-demo/blob/main/FingerprintProDemo/PrivacyInfo.xcprivacy) that we use for our Fingerprint Pro Demo app.

Hope that this information will help to resolve your issue.
