### ISSUE TITLE
Duplicate deviceID

### ISSUE THREAD

**Issue by danilone123** [fingerprintjs/fingerprintjs-ios#51]
Hi , 
I am having an issue with the deviceID generated by the library, is it possible that a deviceID generated by device A could have the same value as another one generated by device B ? 
thanks .

**Comment by mgutski** [comment]
Hi,

The device ID obtained through `Fingerprinter::getDeviceId()` is essentially a Keychain-backed [identifierForVendor](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor/) that is tied to the device. Such an identifier uniquely identifies a device to the app’s vendor, and so it is not possible for the two different devices to have the same ID.

However, opposite to the above, it is perfectly possible for the two devices to have the same **device fingerprint**, as obtained through `Fingerprinter::getFingerprint()`. For instance, given two iPhone 11s with the exact same specs, it is totally expected for the library to return the same `stable` (see [fingerprint stability levels](https://github.com/fingerprintjs/fingerprintjs-ios?tab=readme-ov-file#fingerprint-stability-levels)) device fingerprint for the two iPhones.

Hope this information will help you to clarify your concerns.

**Comment by mgutski** [comment]
Closing as there are no further comments or questions from the issue's author.
